### PR TITLE
Upgraded callback system. Added a 'reload' method to be used in callback...

### PR DESCRIPTION
**Pull request by o-slash**
First of all many thanks for this Krakatoa! I'd like to share some hopefully useful hacks I've done:
- a callback can now be passed as a function reference
- the callback receives a parameter referencing the current instance of the Krakatoa object
- a 'reload' method has been added to reinitialize the sliders from within a callback.

I was able to use all of this as below to reinitialize sliders when browser resolution changes:

``` javascript
$('.slider').krakatoa(
    width : '100%'
    , height : 'max'
    , callback : function(slider) {
        $( window ).on('resize', function() {
            slider.reload();
        });
    }
);
```

### CODE REVIEW

**Comment by davidlpz** [comment]
Thanks for the upgrade, Marco! It will be very useful :D But which browser are you using? I'm testing it with chrome and when I resize the window, the slider gets a height of 0 (it doesn't make sense...).

In Firefox it appears to works fine.

**Comment by o-slash** [comment]
Uhm, I'm experimenting the same issue on the example page. It's strange cause on my website all works fine on every browser, even mobile ones. I'll try to figure out...

**Comment by davidlpz** [comment]
Could you give me the link so I can check too?

**Comment by davidlpz** [comment]
I've been checking this but I still don't get it. If the callback is something like this, it works:

```
callback : function(slider) {
        // Some code
        slider.reload();
    }
```

But the moment you put it inside another function, like your example (an event, a setInterval or something like that), Chrome says the width and height of the images are 0. With text seems to work fine. In firefox works fine too.

**Pull request merged**
